PHPチャレンジ課題1
kenchan1979/furiPHP_exercise pull request #8
Opened 2021-11-16 11:52 UTC by kenchan1979

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/06.md

### メッセージ
challenge1の課題全て完了しました。
確認お願いします😄

2021-11-16 12:17 UTC, kazu-taka requested changes
@kenchan1979 
いくつかコメントしましたので、確認お願いします😊

2021-11-16 12:17 UTC, kazu-taka commented on challenge1_2.php
> +echo '今日は"クリスマス"です。';
@kenchan1979 
出力結果としては間違っていませんが、エスケープ処理を入れて頂く課題ですので、修正お願いします:bow:

2021-11-16 12:17 UTC, kazu-taka commented on challenge1_3.php
> +    for($i = 0; $i < 3; $i++) {
@kenchan1979 
for文を使用してしまうと、万が一teac_dが追加され、all_teamsにも追加された場合に、修正しなければいけなくなってしまいます😊
そのような場合でも、`$all_teams = [$team_a, $team_b, $team_c];`より下のコードを修正しなくても良いように、プログラムの修正をお願いします✨

2021-11-16 12:17 UTC, kazu-taka commented on challenge1_5.php
> +echo "敵を倒した！";
@kenchan1979 
インデントを修正して頂いてから確認するので、まずはインデントの修正をお願いします🙏

2021-11-16 12:25 UTC, kenchan1979 commented
1_5.phpのインデントだけ修正しました。確認お願いします😄

2021-11-16 12:43 UTC, kazu-taka commented on challenge1_5.php
> +        $hp -= $damage;
@kenchan1979 
`$gap = $hp - $damage;`のところで現在のHPからダメージを引いているので、`$gap`を使用しなくても良いコードに修正することも可能です😊
時間があったら修正お願いします✨

2021-11-16 13:52 UTC, kazu-taka commented on challenge1_2.php
> +echo '今日は"クリスマス"です。';
@kenchan1979 
エスケープとはエスケープシーケンスの事でした^^;
https://www.javadrive.jp/php/string/index4.html

2021-11-16 13:54 UTC, kazu-taka commented on challenge1_3.php
> +    for($i = 0; $i < 3; $i++) {
@kenchan1979 
foreachで取り出した`$team`は、配列です。
配列に対してループ処理をさせるというのはすでに使用しているので、そこを意識してコーディングしてみて下さい😊

2021-11-17 00:19 UTC, kenchan1979 commented on challenge1_2.php
> +echo '今日は"クリスマス"です。';
こちらのサイトは初めに参照してしましたが、できなくpc再起動したらできました。以前のdockerの設定時もそうでしたが、稀にこう言ったことが起きます😅

2021-11-17 00:19 UTC, kenchan1979 commented on challenge1_3.php
> +    for($i = 0; $i < 3; $i++) {
すごくシンプルに修正したのですが、合っているのでしょうか？

2021-11-17 00:23 UTC, kenchan1979 commented on challenge1_2.php
> +echo '今日は"クリスマス"です。';
こちらのサイトは初めに参照してしましたが、できなくpc再起動したらできました。以前のdockerの設定時もそうでしたが、稀にこう言ったことが起きます😅

2021-11-17 01:09 UTC, Arisaarisa reviewed
いくつかコメントしました！確認よろしくお願いします🙏
challenge1_5.php 改行についてはすべて`PHP_EOL`に変更しましょう！

2021-11-17 01:09 UTC, Arisaarisa commented on challenge1_5.php
> +        if ($hp > 0) {
if ($hp - $damege > 0) {
この状態でコードの変更を考えてみて下さい:pray:

2021-11-17 01:09 UTC, Arisaarisa commented on challenge1_5.php
> +    if ($input == 1 || $input == 2 || $input == 3) {
ここでは`switch`文を使用します！
```
case 1:
case 2:
case 3:
```
に振り分けてみてください:blush:

2021-11-17 02:26 UTC, kenchan1979 commented on challenge1_3.php
> +foreach($all_teams as $team) {
こちらforeachを複数使って良かったのですか？
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/06.md
こちらには
『foreachを使用して処理する。(ただし、foreachで参照するのは$all_teamsのみ)』
とありましたので、使ってはいけないものかと💦

2021-11-17 03:36 UTC, kenchan1979 commented on challenge1_5.php
> +        if ($hp > 0) {
これをやる理由は何でしょうか？昨日高橋さんから
https://github.com/kenchan1979/furiPHP_exercise/pull/8#discussion_r750233359
とコメントをもらったので修正したのですが？

2021-11-17 04:05 UTC, Arisaarisa commented on challenge1_3.php
> +foreach($all_teams as $team) {
`foreachを使用して処理する。(ただし、foreachで参照するのは$all_teamsのみ)`についてですが、今回の場合は
`foreachで$all_teamsの中で`もう一度foreachをかけるので$all_teamsのみを参照していることになると思います！
課題がわかりずらくて申し訳ありません:sweat:

2021-11-17 04:14 UTC, kenchan1979 commented on challenge1_3.php
> +foreach($all_teams as $team) {
わかりました😄

2021-11-17 04:50 UTC, Arisaarisa commented on challenge1_3.php
> +foreach($all_teams as $team) {
追伸します！
今回foreachの中でforeachを回してもらいたい理由として、後から配列を追加した時にもそのままコードが使えるためです:blush:
https://github.com/kenchan1979/furiPHP_exercise/pull/8#discussion_r750294921

問題の説明が分かりづらく申し訳ありませんでした 💦課題は説明を修正しました:bow:

2021-11-17 04:54 UTC, Arisaarisa commented on challenge1_5.php
> +        if ($hp > 0) {
確かに
` $hp -= $damage;`の部分はそのまま使います！
ただ、`HP - 攻撃力 > 0 の判定`の中で行うため、入力場所が異なります！

`if ($hp - $damege > 0) {`の中で
`trueの時`は`$hp -= $damage;`、
`falseの時`は`HPが0`という流れになります。
わかりそうでしょうか:interrobang:


また、Whileによる出力以降についてはまずswith文の中で行うとスッキリしたコードになります:blush:

2021-11-17 05:24 UTC, kenchan1979 commented on challenge1_5.php
> +        if ($hp > 0) {
ちょっと整理できてないのもあると思いますが、現在のコードだと動くのですが変更するとどうもうまくいきません。。
チャート通りにはできてないでしょうか？

2021-11-17 06:11 UTC, Arisaarisa commented on challenge1_5.php
> +        if ($hp > 0) {
一度ゆっくり整理してみましょう:blush:
流れとしては
```
もしHP-攻撃力 > 0の判定をした時、
trueであれば、HP -= ダメージ
falseであれば、HP = 0 
結果を出力して
break
```
という流れになります:relaxed:

2021-11-18 02:07 UTC, kazu-taka requested changes
@kenchan1979 
コメントしたので修正お願いします:bow:

2021-11-18 02:07 UTC, kazu-taka commented on challenge1_3.php
>  }
@kenchan1979 
インデントが半角スペース8になっているので、フォーマッターを使用しても良いので修正お願いします✨

2021-11-18 02:07 UTC, kazu-taka commented on challenge1_5.php
> +    echo "1.剣 2.魔法 3.打撃", PHP_EOL;
@kenchan1979 
文字列を連結する場合はドットになります✨

2021-11-18 02:48 UTC, kenchan1979 commented
確認お願いします😊

2021-11-18 02:49 UTC, kenchan1979 commented on challenge1_3.php
>  }
わかりました☺️

2021-11-18 04:18 UTC, kzri4 reviewed
一点だけコメントしましたので確認お願いします😊

2021-11-18 04:18 UTC, kzri4 commented on challenge1_5.php
> +    echo "攻撃技は？", PHP_EOL, 1 . ".剣 " . 2 . ".魔法 " . 3 . ".打撃", PHP_EOL;
`攻撃技は？`以降の選択肢ですが、ベタ書きでも出力は問題ないですが、今後攻撃技が増えた際や減った際に手間なく修正できるように連想配列を使用して同様に出力されるようにしてみて下さい😊

2021-11-18 06:04 UTC, kzri4 commented
問題ないのでマージしてOKです😊

2021-11-18 06:19 UTC, merged

2021-11-18 06:19 UTC, kenchan1979 commented
わかりました😄